---
title: "STA 440 Case 4: Root Growth"
author: "Yura Heo, Anirudh Jain, Richard Jiang"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
format: 
  pdf:
    documentclass: article
    fontsize: 11pt
geometry: margin=1in
execute: 
  warning: false
  message: false
  echo: false
---

# Background and Motivation

Researchers developed a new stroke awareness program with the goal of reducing the time needed to provide patients with life-saving acute stroke care delivery. The investigation was divided into two time periods: the pre-treatment period, during which researchers developed the program, and the program implementation period, which overlapped with the onset of the COVID-19 pandemic. The goals of the investigation are twofold: to determine the factors associated with “good” stroke care outcomes, defined as a discharge to home or a rehabilitation facility, and to determine if the implementation of the program improved patient outcomes.

# Data and Exploratory Data Analysis

The researchers tracked stroke patient data from 2019-2020 on a quarterly basis, recording a variety of covariate variables, patient demographic information, and the hospital site where treatment took place. The resulting data set had missing data: therefore, it was necessary for us to develop an approach to handling the missingness before creating any models. In the exploratory analysis phase, we sought to first determine if data missingness was missing at random, missing completely at random, or missing not at random. Our findings on data missingness were used to inform our approach to creating an appropriate model for patient outcomes. Because one goal of the investigation is to determine the effectiveness of the program implementation relative to pre-implementation, we divided the time into three periods: a baseline period (Y1Q1-Y1Q2), a middle transition period as the program was first implemented (Y1Q3-Y2Q2), and the final implementation period (Y2Q3-Y2Q4), where the effects of the program might be the most detectable. 

To begin our analysis, we first sought to determine which variables were most frequently missing. Figure 1 reveals that the 4 variables with missing data were, in descending order, patient age, whether the patient was transported to the hospital via car or EMS, if the hospital was notified prior to patient arrival if they were transported by EMS, and patient race. To determine whether the data is missing completely at random, we investigated whether there were patterns to the missingness. Figures 2 and 3 are heatmaps visualizing the proportion of data missing from the variables. Figure 2 displays the proportion of missingness in each variable by our three time periods, while Figure 3 displays variable missingness by hospital site. Inspection of Figure 2 reveals that data missingness appears worse for certain time quarters, most severely with missing age in the first period. Figure 3 reveals that certain hospitals, namely site IDs 140, 150, and 170, had high variable missingness, with age being the most frequently missing.



# Model Rationale and Implementation

## Rationale

## Evaluation

# Results

# Conclusion

# Limitations and Future Directions

# Appendix